// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brakingInfoReport.proto

package com.lyh.protobuf.demo.business;

public final class BrakingInfoReportProto {
  private BrakingInfoReportProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BrakingInfoReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coom.lyh.protobuf.demo.protos.BrakingInfoReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.JsonMessageType jsonMessageType = 1;</code>
     */
    int getJsonMessageTypeValue();
    /**
     * <code>.JsonMessageType jsonMessageType = 1;</code>
     */
    Common.JsonMessageType getJsonMessageType();

    /**
     * <code>.ObjectMessageType objectMessageType = 2;</code>
     */
    int getObjectMessageTypeValue();
    /**
     * <code>.ObjectMessageType objectMessageType = 2;</code>
     */
    Common.ObjectMessageType getObjectMessageType();

    /**
     * <code>string protocol = 3;</code>
     */
    java.lang.String getProtocol();
    /**
     * <code>string protocol = 3;</code>
     */
    com.google.protobuf.ByteString
        getProtocolBytes();

    /**
     * <pre>
     **
     * 车辆唯一标示
     * </pre>
     *
     * <code>string sn = 4;</code>
     */
    java.lang.String getSn();
    /**
     * <pre>
     **
     * 车辆唯一标示
     * </pre>
     *
     * <code>string sn = 4;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    /**
     * <pre>
     **
     * 车型ID
     * </pre>
     *
     * <code>string carModelId = 5;</code>
     */
    java.lang.String getCarModelId();
    /**
     * <pre>
     **
     * 车型ID
     * </pre>
     *
     * <code>string carModelId = 5;</code>
     */
    com.google.protobuf.ByteString
        getCarModelIdBytes();

    /**
     * <pre>
     **
     * 消息传输时间(单位毫秒)
     * </pre>
     *
     * <code>int64 ts = 6;</code>
     */
    long getTs();

    /**
     * <pre>
     **
     * 时间类型
     * </pre>
     *
     * <code>string et = 7;</code>
     */
    java.lang.String getEt();
    /**
     * <pre>
     **
     * 时间类型
     * </pre>
     *
     * <code>string et = 7;</code>
     */
    com.google.protobuf.ByteString
        getEtBytes();

    /**
     * <pre>
     **
     * 行程ID
     * </pre>
     *
     * <code>int32 tripId = 8;</code>
     */
    int getTripId();

    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    java.util.List<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo> 
        getDataList();
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo getData(int index);
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    java.util.List<? extends com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code coom.lyh.protobuf.demo.protos.BrakingInfoReport}
   */
  public  static final class BrakingInfoReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:coom.lyh.protobuf.demo.protos.BrakingInfoReport)
      BrakingInfoReportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BrakingInfoReport.newBuilder() to construct.
    private BrakingInfoReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BrakingInfoReport() {
      jsonMessageType_ = 0;
      objectMessageType_ = 0;
      protocol_ = "";
      sn_ = "";
      carModelId_ = "";
      et_ = "";
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BrakingInfoReport();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BrakingInfoReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              jsonMessageType_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              objectMessageType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              protocol_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              sn_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              carModelId_ = s;
              break;
            }
            case 48: {

              ts_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              et_ = s;
              break;
            }
            case 64: {

              tripId_ = input.readInt32();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.class, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.Builder.class);
    }

    public interface BrakingInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *private Long rts;
       * </pre>
       *
       * <code>int64 rts = 1;</code>
       */
      long getRts();

      /**
       * <pre>
       *private Float bol;
       * </pre>
       *
       * <code>float bol = 2;</code>
       */
      float getBol();
    }
    /**
     * <pre>
     **
     * 事件产生的时间(单位毫秒)
     * </pre>
     *
     * Protobuf type {@code coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo}
     */
    public  static final class BrakingInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo)
        BrakingInfoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use BrakingInfo.newBuilder() to construct.
      private BrakingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private BrakingInfo() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new BrakingInfo();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private BrakingInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                rts_ = input.readInt64();
                break;
              }
              case 21: {

                bol_ = input.readFloat();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.class, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder.class);
      }

      public static final int RTS_FIELD_NUMBER = 1;
      private long rts_;
      /**
       * <pre>
       *private Long rts;
       * </pre>
       *
       * <code>int64 rts = 1;</code>
       */
      public long getRts() {
        return rts_;
      }

      public static final int BOL_FIELD_NUMBER = 2;
      private float bol_;
      /**
       * <pre>
       *private Float bol;
       * </pre>
       *
       * <code>float bol = 2;</code>
       */
      public float getBol() {
        return bol_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (rts_ != 0L) {
          output.writeInt64(1, rts_);
        }
        if (bol_ != 0F) {
          output.writeFloat(2, bol_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (rts_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, rts_);
        }
        if (bol_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, bol_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo)) {
          return super.equals(obj);
        }
        com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo other = (com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo) obj;

        if (getRts()
            != other.getRts()) return false;
        if (java.lang.Float.floatToIntBits(getBol())
            != java.lang.Float.floatToIntBits(
                other.getBol())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + RTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRts());
        hash = (37 * hash) + BOL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getBol());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       **
       * 事件产生的时间(单位毫秒)
       * </pre>
       *
       * Protobuf type {@code coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo)
          com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.class, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder.class);
        }

        // Construct using com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          rts_ = 0L;

          bol_ = 0F;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_descriptor;
        }

        @java.lang.Override
        public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo getDefaultInstanceForType() {
          return com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.getDefaultInstance();
        }

        @java.lang.Override
        public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo build() {
          com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo buildPartial() {
          com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo result = new com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo(this);
          result.rts_ = rts_;
          result.bol_ = bol_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo) {
            return mergeFrom((com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo other) {
          if (other == com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.getDefaultInstance()) return this;
          if (other.getRts() != 0L) {
            setRts(other.getRts());
          }
          if (other.getBol() != 0F) {
            setBol(other.getBol());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long rts_ ;
        /**
         * <pre>
         *private Long rts;
         * </pre>
         *
         * <code>int64 rts = 1;</code>
         */
        public long getRts() {
          return rts_;
        }
        /**
         * <pre>
         *private Long rts;
         * </pre>
         *
         * <code>int64 rts = 1;</code>
         */
        public Builder setRts(long value) {
          
          rts_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *private Long rts;
         * </pre>
         *
         * <code>int64 rts = 1;</code>
         */
        public Builder clearRts() {
          
          rts_ = 0L;
          onChanged();
          return this;
        }

        private float bol_ ;
        /**
         * <pre>
         *private Float bol;
         * </pre>
         *
         * <code>float bol = 2;</code>
         */
        public float getBol() {
          return bol_;
        }
        /**
         * <pre>
         *private Float bol;
         * </pre>
         *
         * <code>float bol = 2;</code>
         */
        public Builder setBol(float value) {
          
          bol_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *private Float bol;
         * </pre>
         *
         * <code>float bol = 2;</code>
         */
        public Builder clearBol() {
          
          bol_ = 0F;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo)
      }

      // @@protoc_insertion_point(class_scope:coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo)
      private static final com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo();
      }

      public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<BrakingInfo>
          PARSER = new com.google.protobuf.AbstractParser<BrakingInfo>() {
        @java.lang.Override
        public BrakingInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BrakingInfo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<BrakingInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<BrakingInfo> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int JSONMESSAGETYPE_FIELD_NUMBER = 1;
    private int jsonMessageType_;
    /**
     * <code>.JsonMessageType jsonMessageType = 1;</code>
     */
    public int getJsonMessageTypeValue() {
      return jsonMessageType_;
    }
    /**
     * <code>.JsonMessageType jsonMessageType = 1;</code>
     */
    public Common.JsonMessageType getJsonMessageType() {
      @SuppressWarnings("deprecation")
      Common.JsonMessageType result = Common.JsonMessageType.valueOf(jsonMessageType_);
      return result == null ? Common.JsonMessageType.UNRECOGNIZED : result;
    }

    public static final int OBJECTMESSAGETYPE_FIELD_NUMBER = 2;
    private int objectMessageType_;
    /**
     * <code>.ObjectMessageType objectMessageType = 2;</code>
     */
    public int getObjectMessageTypeValue() {
      return objectMessageType_;
    }
    /**
     * <code>.ObjectMessageType objectMessageType = 2;</code>
     */
    public Common.ObjectMessageType getObjectMessageType() {
      @SuppressWarnings("deprecation")
      Common.ObjectMessageType result = Common.ObjectMessageType.valueOf(objectMessageType_);
      return result == null ? Common.ObjectMessageType.UNRECOGNIZED : result;
    }

    public static final int PROTOCOL_FIELD_NUMBER = 3;
    private volatile java.lang.Object protocol_;
    /**
     * <code>string protocol = 3;</code>
     */
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      }
    }
    /**
     * <code>string protocol = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SN_FIELD_NUMBER = 4;
    private volatile java.lang.Object sn_;
    /**
     * <pre>
     **
     * 车辆唯一标示
     * </pre>
     *
     * <code>string sn = 4;</code>
     */
    public java.lang.String getSn() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 车辆唯一标示
     * </pre>
     *
     * <code>string sn = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARMODELID_FIELD_NUMBER = 5;
    private volatile java.lang.Object carModelId_;
    /**
     * <pre>
     **
     * 车型ID
     * </pre>
     *
     * <code>string carModelId = 5;</code>
     */
    public java.lang.String getCarModelId() {
      java.lang.Object ref = carModelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        carModelId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 车型ID
     * </pre>
     *
     * <code>string carModelId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCarModelIdBytes() {
      java.lang.Object ref = carModelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        carModelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 6;
    private long ts_;
    /**
     * <pre>
     **
     * 消息传输时间(单位毫秒)
     * </pre>
     *
     * <code>int64 ts = 6;</code>
     */
    public long getTs() {
      return ts_;
    }

    public static final int ET_FIELD_NUMBER = 7;
    private volatile java.lang.Object et_;
    /**
     * <pre>
     **
     * 时间类型
     * </pre>
     *
     * <code>string et = 7;</code>
     */
    public java.lang.String getEt() {
      java.lang.Object ref = et_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        et_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 时间类型
     * </pre>
     *
     * <code>string et = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEtBytes() {
      java.lang.Object ref = et_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        et_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIPID_FIELD_NUMBER = 8;
    private int tripId_;
    /**
     * <pre>
     **
     * 行程ID
     * </pre>
     *
     * <code>int32 tripId = 8;</code>
     */
    public int getTripId() {
      return tripId_;
    }

    public static final int DATA_FIELD_NUMBER = 9;
    private java.util.List<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo> data_;
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    public java.util.List<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    public java.util.List<? extends com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
     */
    public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (jsonMessageType_ != Common.JsonMessageType.REPORT.getNumber()) {
        output.writeEnum(1, jsonMessageType_);
      }
      if (objectMessageType_ != Common.ObjectMessageType.CONNECT_REQUEST.getNumber()) {
        output.writeEnum(2, objectMessageType_);
      }
      if (!getProtocolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, protocol_);
      }
      if (!getSnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sn_);
      }
      if (!getCarModelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, carModelId_);
      }
      if (ts_ != 0L) {
        output.writeInt64(6, ts_);
      }
      if (!getEtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, et_);
      }
      if (tripId_ != 0) {
        output.writeInt32(8, tripId_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(9, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (jsonMessageType_ != Common.JsonMessageType.REPORT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, jsonMessageType_);
      }
      if (objectMessageType_ != Common.ObjectMessageType.CONNECT_REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, objectMessageType_);
      }
      if (!getProtocolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, protocol_);
      }
      if (!getSnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sn_);
      }
      if (!getCarModelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, carModelId_);
      }
      if (ts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, ts_);
      }
      if (!getEtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, et_);
      }
      if (tripId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, tripId_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport)) {
        return super.equals(obj);
      }
      com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport other = (com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport) obj;

      if (jsonMessageType_ != other.jsonMessageType_) return false;
      if (objectMessageType_ != other.objectMessageType_) return false;
      if (!getProtocol()
          .equals(other.getProtocol())) return false;
      if (!getSn()
          .equals(other.getSn())) return false;
      if (!getCarModelId()
          .equals(other.getCarModelId())) return false;
      if (getTs()
          != other.getTs()) return false;
      if (!getEt()
          .equals(other.getEt())) return false;
      if (getTripId()
          != other.getTripId()) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSONMESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + jsonMessageType_;
      hash = (37 * hash) + OBJECTMESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + objectMessageType_;
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocol().hashCode();
      hash = (37 * hash) + SN_FIELD_NUMBER;
      hash = (53 * hash) + getSn().hashCode();
      hash = (37 * hash) + CARMODELID_FIELD_NUMBER;
      hash = (53 * hash) + getCarModelId().hashCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTs());
      hash = (37 * hash) + ET_FIELD_NUMBER;
      hash = (53 * hash) + getEt().hashCode();
      hash = (37 * hash) + TRIPID_FIELD_NUMBER;
      hash = (53 * hash) + getTripId();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coom.lyh.protobuf.demo.protos.BrakingInfoReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coom.lyh.protobuf.demo.protos.BrakingInfoReport)
        com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.class, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.Builder.class);
      }

      // Construct using com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jsonMessageType_ = 0;

        objectMessageType_ = 0;

        protocol_ = "";

        sn_ = "";

        carModelId_ = "";

        ts_ = 0L;

        et_ = "";

        tripId_ = 0;

        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lyh.protobuf.demo.business.BrakingInfoReportProto.internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_descriptor;
      }

      @java.lang.Override
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport getDefaultInstanceForType() {
        return com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.getDefaultInstance();
      }

      @java.lang.Override
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport build() {
        com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport buildPartial() {
        com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport result = new com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport(this);
        int from_bitField0_ = bitField0_;
        result.jsonMessageType_ = jsonMessageType_;
        result.objectMessageType_ = objectMessageType_;
        result.protocol_ = protocol_;
        result.sn_ = sn_;
        result.carModelId_ = carModelId_;
        result.ts_ = ts_;
        result.et_ = et_;
        result.tripId_ = tripId_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport) {
          return mergeFrom((com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport other) {
        if (other == com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.getDefaultInstance()) return this;
        if (other.jsonMessageType_ != 0) {
          setJsonMessageTypeValue(other.getJsonMessageTypeValue());
        }
        if (other.objectMessageType_ != 0) {
          setObjectMessageTypeValue(other.getObjectMessageTypeValue());
        }
        if (!other.getProtocol().isEmpty()) {
          protocol_ = other.protocol_;
          onChanged();
        }
        if (!other.getSn().isEmpty()) {
          sn_ = other.sn_;
          onChanged();
        }
        if (!other.getCarModelId().isEmpty()) {
          carModelId_ = other.carModelId_;
          onChanged();
        }
        if (other.getTs() != 0L) {
          setTs(other.getTs());
        }
        if (!other.getEt().isEmpty()) {
          et_ = other.et_;
          onChanged();
        }
        if (other.getTripId() != 0) {
          setTripId(other.getTripId());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int jsonMessageType_ = 0;
      /**
       * <code>.JsonMessageType jsonMessageType = 1;</code>
       */
      public int getJsonMessageTypeValue() {
        return jsonMessageType_;
      }
      /**
       * <code>.JsonMessageType jsonMessageType = 1;</code>
       */
      public Builder setJsonMessageTypeValue(int value) {
        jsonMessageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.JsonMessageType jsonMessageType = 1;</code>
       */
      public Common.JsonMessageType getJsonMessageType() {
        @SuppressWarnings("deprecation")
        Common.JsonMessageType result = Common.JsonMessageType.valueOf(jsonMessageType_);
        return result == null ? Common.JsonMessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.JsonMessageType jsonMessageType = 1;</code>
       */
      public Builder setJsonMessageType(Common.JsonMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        jsonMessageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.JsonMessageType jsonMessageType = 1;</code>
       */
      public Builder clearJsonMessageType() {
        
        jsonMessageType_ = 0;
        onChanged();
        return this;
      }

      private int objectMessageType_ = 0;
      /**
       * <code>.ObjectMessageType objectMessageType = 2;</code>
       */
      public int getObjectMessageTypeValue() {
        return objectMessageType_;
      }
      /**
       * <code>.ObjectMessageType objectMessageType = 2;</code>
       */
      public Builder setObjectMessageTypeValue(int value) {
        objectMessageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ObjectMessageType objectMessageType = 2;</code>
       */
      public Common.ObjectMessageType getObjectMessageType() {
        @SuppressWarnings("deprecation")
        Common.ObjectMessageType result = Common.ObjectMessageType.valueOf(objectMessageType_);
        return result == null ? Common.ObjectMessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ObjectMessageType objectMessageType = 2;</code>
       */
      public Builder setObjectMessageType(Common.ObjectMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        objectMessageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ObjectMessageType objectMessageType = 2;</code>
       */
      public Builder clearObjectMessageType() {
        
        objectMessageType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object protocol_ = "";
      /**
       * <code>string protocol = 3;</code>
       */
      public java.lang.String getProtocol() {
        java.lang.Object ref = protocol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          protocol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string protocol = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProtocolBytes() {
        java.lang.Object ref = protocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string protocol = 3;</code>
       */
      public Builder setProtocol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 3;</code>
       */
      public Builder clearProtocol() {
        
        protocol_ = getDefaultInstance().getProtocol();
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 3;</code>
       */
      public Builder setProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        protocol_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sn_ = "";
      /**
       * <pre>
       **
       * 车辆唯一标示
       * </pre>
       *
       * <code>string sn = 4;</code>
       */
      public java.lang.String getSn() {
        java.lang.Object ref = sn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 车辆唯一标示
       * </pre>
       *
       * <code>string sn = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        java.lang.Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 车辆唯一标示
       * </pre>
       *
       * <code>string sn = 4;</code>
       */
      public Builder setSn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 车辆唯一标示
       * </pre>
       *
       * <code>string sn = 4;</code>
       */
      public Builder clearSn() {
        
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 车辆唯一标示
       * </pre>
       *
       * <code>string sn = 4;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sn_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object carModelId_ = "";
      /**
       * <pre>
       **
       * 车型ID
       * </pre>
       *
       * <code>string carModelId = 5;</code>
       */
      public java.lang.String getCarModelId() {
        java.lang.Object ref = carModelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          carModelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 车型ID
       * </pre>
       *
       * <code>string carModelId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCarModelIdBytes() {
        java.lang.Object ref = carModelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carModelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 车型ID
       * </pre>
       *
       * <code>string carModelId = 5;</code>
       */
      public Builder setCarModelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        carModelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 车型ID
       * </pre>
       *
       * <code>string carModelId = 5;</code>
       */
      public Builder clearCarModelId() {
        
        carModelId_ = getDefaultInstance().getCarModelId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 车型ID
       * </pre>
       *
       * <code>string carModelId = 5;</code>
       */
      public Builder setCarModelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        carModelId_ = value;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <pre>
       **
       * 消息传输时间(单位毫秒)
       * </pre>
       *
       * <code>int64 ts = 6;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <pre>
       **
       * 消息传输时间(单位毫秒)
       * </pre>
       *
       * <code>int64 ts = 6;</code>
       */
      public Builder setTs(long value) {
        
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 消息传输时间(单位毫秒)
       * </pre>
       *
       * <code>int64 ts = 6;</code>
       */
      public Builder clearTs() {
        
        ts_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object et_ = "";
      /**
       * <pre>
       **
       * 时间类型
       * </pre>
       *
       * <code>string et = 7;</code>
       */
      public java.lang.String getEt() {
        java.lang.Object ref = et_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          et_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 时间类型
       * </pre>
       *
       * <code>string et = 7;</code>
       */
      public com.google.protobuf.ByteString
          getEtBytes() {
        java.lang.Object ref = et_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          et_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 时间类型
       * </pre>
       *
       * <code>string et = 7;</code>
       */
      public Builder setEt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        et_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 时间类型
       * </pre>
       *
       * <code>string et = 7;</code>
       */
      public Builder clearEt() {
        
        et_ = getDefaultInstance().getEt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 时间类型
       * </pre>
       *
       * <code>string et = 7;</code>
       */
      public Builder setEtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        et_ = value;
        onChanged();
        return this;
      }

      private int tripId_ ;
      /**
       * <pre>
       **
       * 行程ID
       * </pre>
       *
       * <code>int32 tripId = 8;</code>
       */
      public int getTripId() {
        return tripId_;
      }
      /**
       * <pre>
       **
       * 行程ID
       * </pre>
       *
       * <code>int32 tripId = 8;</code>
       */
      public Builder setTripId(int value) {
        
        tripId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 行程ID
       * </pre>
       *
       * <code>int32 tripId = 8;</code>
       */
      public Builder clearTripId() {
        
        tripId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder> dataBuilder_;

      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public java.util.List<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder setData(
          int index, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder setData(
          int index, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder addData(com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder addData(
          int index, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder addData(
          com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder addData(
          int index, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public java.util.List<? extends com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .coom.lyh.protobuf.demo.protos.BrakingInfoReport.BrakingInfo data = 9;</code>
       */
      public java.util.List<com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfo.Builder, com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport.BrakingInfoOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:coom.lyh.protobuf.demo.protos.BrakingInfoReport)
    }

    // @@protoc_insertion_point(class_scope:coom.lyh.protobuf.demo.protos.BrakingInfoReport)
    private static final com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport();
    }

    public static com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BrakingInfoReport>
        PARSER = new com.google.protobuf.AbstractParser<BrakingInfoReport>() {
      @java.lang.Override
      public BrakingInfoReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BrakingInfoReport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BrakingInfoReport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BrakingInfoReport> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lyh.protobuf.demo.business.BrakingInfoReportProto.BrakingInfoReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027brakingInfoReport.proto\022\035coom.lyh.prot" +
      "obuf.demo.protos\032\014common.proto\"\274\002\n\021Braki" +
      "ngInfoReport\022)\n\017jsonMessageType\030\001 \001(\0162\020." +
      "JsonMessageType\022-\n\021objectMessageType\030\002 \001" +
      "(\0162\022.ObjectMessageType\022\020\n\010protocol\030\003 \001(\t" +
      "\022\n\n\002sn\030\004 \001(\t\022\022\n\ncarModelId\030\005 \001(\t\022\n\n\002ts\030\006" +
      " \001(\003\022\n\n\002et\030\007 \001(\t\022\016\n\006tripId\030\010 \001(\005\022J\n\004data" +
      "\030\t \003(\0132<.coom.lyh.protobuf.demo.protos.B" +
      "rakingInfoReport.BrakingInfo\032\'\n\013BrakingI" +
      "nfo\022\013\n\003rts\030\001 \001(\003\022\013\n\003bol\030\002 \001(\002B8\n\036com.lyh" +
      ".protobuf.demo.businessB\026BrakingInfoRepo" +
      "rtProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.getDescriptor(),
        });
    internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_descriptor,
        new java.lang.String[] { "JsonMessageType", "ObjectMessageType", "Protocol", "Sn", "CarModelId", "Ts", "Et", "TripId", "Data", });
    internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_descriptor =
      internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_descriptor.getNestedTypes().get(0);
    internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coom_lyh_protobuf_demo_protos_BrakingInfoReport_BrakingInfo_descriptor,
        new java.lang.String[] { "Rts", "Bol", });
    Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
