// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.lyh.protobuf.demo.business;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code JsonMessageType}
   */
  public enum JsonMessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REPORT = 0;</code>
     */
    REPORT(0),
    /**
     * <code>REQUEST = 1;</code>
     */
    REQUEST(1),
    /**
     * <code>RESPONSE = 2;</code>
     */
    RESPONSE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REPORT = 0;</code>
     */
    public static final int REPORT_VALUE = 0;
    /**
     * <code>REQUEST = 1;</code>
     */
    public static final int REQUEST_VALUE = 1;
    /**
     * <code>RESPONSE = 2;</code>
     */
    public static final int RESPONSE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static JsonMessageType valueOf(int value) {
      return forNumber(value);
    }

    public static JsonMessageType forNumber(int value) {
      switch (value) {
        case 0: return REPORT;
        case 1: return REQUEST;
        case 2: return RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<JsonMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        JsonMessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<JsonMessageType>() {
            public JsonMessageType findValueByNumber(int number) {
              return JsonMessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lyh.protobuf.demo.business.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final JsonMessageType[] VALUES = values();

    public static JsonMessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private JsonMessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:JsonMessageType)
  }

  /**
   * Protobuf enum {@code ObjectMessageType}
   */
  public enum ObjectMessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     **
     * 连接请求
     * </pre>
     *
     * <code>CONNECT_REQUEST = 0;</code>
     */
    CONNECT_REQUEST(0),
    /**
     * <pre>
     **
     * 连接响应
     * </pre>
     *
     * <code>CONNECT_RESPONSE = 1;</code>
     */
    CONNECT_RESPONSE(1),
    /**
     * <pre>
     **
     * 注册请求
     * </pre>
     *
     * <code>REGISTER_REQUEST = 2;</code>
     */
    REGISTER_REQUEST(2),
    /**
     * <pre>
     **
     * 注册响应
     * </pre>
     *
     * <code>REGISTER_RESPONSE = 3;</code>
     */
    REGISTER_RESPONSE(3),
    /**
     * <pre>
     **
     * 登出请求
     * </pre>
     *
     * <code>LOGOUT_REQUEST = 4;</code>
     */
    LOGOUT_REQUEST(4),
    /**
     * <pre>
     **
     * 登出响应
     * </pre>
     *
     * <code>LOGOUT_RESPONSE = 5;</code>
     */
    LOGOUT_RESPONSE(5),
    /**
     * <pre>
     **
     *下发消息请求
     * </pre>
     *
     * <code>PUSH_MESSAGE_REQUEST = 6;</code>
     */
    PUSH_MESSAGE_REQUEST(6),
    /**
     * <pre>
     * 下发消息响应
     * </pre>
     *
     * <code>PUSH_MESSAGE_RESPONSE = 7;</code>
     */
    PUSH_MESSAGE_RESPONSE(7),
    /**
     * <code>CONNECT_STATUS_REPORT = 8;</code>
     */
    CONNECT_STATUS_REPORT(8),
    /**
     * <pre>
     **
     * 轨迹数据
     * </pre>
     *
     * <code>REPORT_GPS_DATA = 9;</code>
     */
    REPORT_GPS_DATA(9),
    /**
     * <pre>
     **
     * 油量消息
     * </pre>
     *
     * <code>REPORT_REMAINED_OIL = 10;</code>
     */
    REPORT_REMAINED_OIL(10),
    /**
     * <pre>
     **
     * 车辆状态消息
     * </pre>
     *
     * <code>REPORT_CAR_STATUS = 11;</code>
     */
    REPORT_CAR_STATUS(11),
    /**
     * <pre>
     **
     * 环境数据消息
     * </pre>
     *
     * <code>REPORT_ENVIRONMENT_DATA = 12;</code>
     */
    REPORT_ENVIRONMENT_DATA(12),
    /**
     * <pre>
     **
     * 驾驶状态消息
     * </pre>
     *
     * <code>REPORT_DRIVE_STATUS = 13;</code>
     */
    REPORT_DRIVE_STATUS(13),
    /**
     * <pre>
     **
     * 油耗消息
     * </pre>
     *
     * <code>REPORT_OIL_CONSUMPTION = 14;</code>
     */
    REPORT_OIL_CONSUMPTION(14),
    /**
     * <pre>
     **
     * 驾驶行为消息
     * </pre>
     *
     * <code>REPORT_DRIVE_BEHAVIOR = 15;</code>
     */
    REPORT_DRIVE_BEHAVIOR(15),
    /**
     * <pre>
     **
     * 行驶速度消息
     * </pre>
     *
     * <code>REPORT_DRIVE_SPEED = 16;</code>
     */
    REPORT_DRIVE_SPEED(16),
    /**
     * <pre>
     **
     * 发动机转速消息
     * </pre>
     *
     * <code>REPORT_ENGINE_SPEED = 17;</code>
     */
    REPORT_ENGINE_SPEED(17),
    /**
     * <pre>
     **
     * 发动机状态消息
     * </pre>
     *
     * <code>REPORT_ENGINE_STATUS = 18;</code>
     */
    REPORT_ENGINE_STATUS(18),
    /**
     * <pre>
     **
     * 制动系统消息
     * </pre>
     *
     * <code>REPORT_BRAKING_INFO = 19;</code>
     */
    REPORT_BRAKING_INFO(19),
    /**
     * <pre>
     **
     * 行程开始
     * </pre>
     *
     * <code>REPORT_TRIP_START = 20;</code>
     */
    REPORT_TRIP_START(20),
    /**
     * <pre>
     **
     * 车辆警报消息
     * </pre>
     *
     * <code>REPORT_CAR_WARN = 21;</code>
     */
    REPORT_CAR_WARN(21),
    /**
     * <pre>
     **
     * 行程结束
     * </pre>
     *
     * <code>REPORT_TRIP_END = 22;</code>
     */
    REPORT_TRIP_END(22),
    /**
     * <pre>
     **
     * 轮胎消息
     * </pre>
     *
     * <code>REPORT_TYRE_INFO = 23;</code>
     */
    REPORT_TYRE_INFO(23),
    /**
     * <pre>
     **
     * broker信息上报
     * </pre>
     *
     * <code>IOT_BROKER_INFO = 24;</code>
     */
    IOT_BROKER_INFO(24),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     **
     * 连接请求
     * </pre>
     *
     * <code>CONNECT_REQUEST = 0;</code>
     */
    public static final int CONNECT_REQUEST_VALUE = 0;
    /**
     * <pre>
     **
     * 连接响应
     * </pre>
     *
     * <code>CONNECT_RESPONSE = 1;</code>
     */
    public static final int CONNECT_RESPONSE_VALUE = 1;
    /**
     * <pre>
     **
     * 注册请求
     * </pre>
     *
     * <code>REGISTER_REQUEST = 2;</code>
     */
    public static final int REGISTER_REQUEST_VALUE = 2;
    /**
     * <pre>
     **
     * 注册响应
     * </pre>
     *
     * <code>REGISTER_RESPONSE = 3;</code>
     */
    public static final int REGISTER_RESPONSE_VALUE = 3;
    /**
     * <pre>
     **
     * 登出请求
     * </pre>
     *
     * <code>LOGOUT_REQUEST = 4;</code>
     */
    public static final int LOGOUT_REQUEST_VALUE = 4;
    /**
     * <pre>
     **
     * 登出响应
     * </pre>
     *
     * <code>LOGOUT_RESPONSE = 5;</code>
     */
    public static final int LOGOUT_RESPONSE_VALUE = 5;
    /**
     * <pre>
     **
     *下发消息请求
     * </pre>
     *
     * <code>PUSH_MESSAGE_REQUEST = 6;</code>
     */
    public static final int PUSH_MESSAGE_REQUEST_VALUE = 6;
    /**
     * <pre>
     * 下发消息响应
     * </pre>
     *
     * <code>PUSH_MESSAGE_RESPONSE = 7;</code>
     */
    public static final int PUSH_MESSAGE_RESPONSE_VALUE = 7;
    /**
     * <code>CONNECT_STATUS_REPORT = 8;</code>
     */
    public static final int CONNECT_STATUS_REPORT_VALUE = 8;
    /**
     * <pre>
     **
     * 轨迹数据
     * </pre>
     *
     * <code>REPORT_GPS_DATA = 9;</code>
     */
    public static final int REPORT_GPS_DATA_VALUE = 9;
    /**
     * <pre>
     **
     * 油量消息
     * </pre>
     *
     * <code>REPORT_REMAINED_OIL = 10;</code>
     */
    public static final int REPORT_REMAINED_OIL_VALUE = 10;
    /**
     * <pre>
     **
     * 车辆状态消息
     * </pre>
     *
     * <code>REPORT_CAR_STATUS = 11;</code>
     */
    public static final int REPORT_CAR_STATUS_VALUE = 11;
    /**
     * <pre>
     **
     * 环境数据消息
     * </pre>
     *
     * <code>REPORT_ENVIRONMENT_DATA = 12;</code>
     */
    public static final int REPORT_ENVIRONMENT_DATA_VALUE = 12;
    /**
     * <pre>
     **
     * 驾驶状态消息
     * </pre>
     *
     * <code>REPORT_DRIVE_STATUS = 13;</code>
     */
    public static final int REPORT_DRIVE_STATUS_VALUE = 13;
    /**
     * <pre>
     **
     * 油耗消息
     * </pre>
     *
     * <code>REPORT_OIL_CONSUMPTION = 14;</code>
     */
    public static final int REPORT_OIL_CONSUMPTION_VALUE = 14;
    /**
     * <pre>
     **
     * 驾驶行为消息
     * </pre>
     *
     * <code>REPORT_DRIVE_BEHAVIOR = 15;</code>
     */
    public static final int REPORT_DRIVE_BEHAVIOR_VALUE = 15;
    /**
     * <pre>
     **
     * 行驶速度消息
     * </pre>
     *
     * <code>REPORT_DRIVE_SPEED = 16;</code>
     */
    public static final int REPORT_DRIVE_SPEED_VALUE = 16;
    /**
     * <pre>
     **
     * 发动机转速消息
     * </pre>
     *
     * <code>REPORT_ENGINE_SPEED = 17;</code>
     */
    public static final int REPORT_ENGINE_SPEED_VALUE = 17;
    /**
     * <pre>
     **
     * 发动机状态消息
     * </pre>
     *
     * <code>REPORT_ENGINE_STATUS = 18;</code>
     */
    public static final int REPORT_ENGINE_STATUS_VALUE = 18;
    /**
     * <pre>
     **
     * 制动系统消息
     * </pre>
     *
     * <code>REPORT_BRAKING_INFO = 19;</code>
     */
    public static final int REPORT_BRAKING_INFO_VALUE = 19;
    /**
     * <pre>
     **
     * 行程开始
     * </pre>
     *
     * <code>REPORT_TRIP_START = 20;</code>
     */
    public static final int REPORT_TRIP_START_VALUE = 20;
    /**
     * <pre>
     **
     * 车辆警报消息
     * </pre>
     *
     * <code>REPORT_CAR_WARN = 21;</code>
     */
    public static final int REPORT_CAR_WARN_VALUE = 21;
    /**
     * <pre>
     **
     * 行程结束
     * </pre>
     *
     * <code>REPORT_TRIP_END = 22;</code>
     */
    public static final int REPORT_TRIP_END_VALUE = 22;
    /**
     * <pre>
     **
     * 轮胎消息
     * </pre>
     *
     * <code>REPORT_TYRE_INFO = 23;</code>
     */
    public static final int REPORT_TYRE_INFO_VALUE = 23;
    /**
     * <pre>
     **
     * broker信息上报
     * </pre>
     *
     * <code>IOT_BROKER_INFO = 24;</code>
     */
    public static final int IOT_BROKER_INFO_VALUE = 24;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ObjectMessageType valueOf(int value) {
      return forNumber(value);
    }

    public static ObjectMessageType forNumber(int value) {
      switch (value) {
        case 0: return CONNECT_REQUEST;
        case 1: return CONNECT_RESPONSE;
        case 2: return REGISTER_REQUEST;
        case 3: return REGISTER_RESPONSE;
        case 4: return LOGOUT_REQUEST;
        case 5: return LOGOUT_RESPONSE;
        case 6: return PUSH_MESSAGE_REQUEST;
        case 7: return PUSH_MESSAGE_RESPONSE;
        case 8: return CONNECT_STATUS_REPORT;
        case 9: return REPORT_GPS_DATA;
        case 10: return REPORT_REMAINED_OIL;
        case 11: return REPORT_CAR_STATUS;
        case 12: return REPORT_ENVIRONMENT_DATA;
        case 13: return REPORT_DRIVE_STATUS;
        case 14: return REPORT_OIL_CONSUMPTION;
        case 15: return REPORT_DRIVE_BEHAVIOR;
        case 16: return REPORT_DRIVE_SPEED;
        case 17: return REPORT_ENGINE_SPEED;
        case 18: return REPORT_ENGINE_STATUS;
        case 19: return REPORT_BRAKING_INFO;
        case 20: return REPORT_TRIP_START;
        case 21: return REPORT_CAR_WARN;
        case 22: return REPORT_TRIP_END;
        case 23: return REPORT_TYRE_INFO;
        case 24: return IOT_BROKER_INFO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ObjectMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ObjectMessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ObjectMessageType>() {
            public ObjectMessageType findValueByNumber(int number) {
              return ObjectMessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lyh.protobuf.demo.business.Common.getDescriptor().getEnumTypes().get(1);
    }

    private static final ObjectMessageType[] VALUES = values();

    public static ObjectMessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ObjectMessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ObjectMessageType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto*8\n\017JsonMessageType\022\n\n\006REP" +
      "ORT\020\000\022\013\n\007REQUEST\020\001\022\014\n\010RESPONSE\020\002*\346\004\n\021Obj" +
      "ectMessageType\022\023\n\017CONNECT_REQUEST\020\000\022\024\n\020C" +
      "ONNECT_RESPONSE\020\001\022\024\n\020REGISTER_REQUEST\020\002\022" +
      "\025\n\021REGISTER_RESPONSE\020\003\022\022\n\016LOGOUT_REQUEST" +
      "\020\004\022\023\n\017LOGOUT_RESPONSE\020\005\022\030\n\024PUSH_MESSAGE_" +
      "REQUEST\020\006\022\031\n\025PUSH_MESSAGE_RESPONSE\020\007\022\031\n\025" +
      "CONNECT_STATUS_REPORT\020\010\022\023\n\017REPORT_GPS_DA" +
      "TA\020\t\022\027\n\023REPORT_REMAINED_OIL\020\n\022\025\n\021REPORT_" +
      "CAR_STATUS\020\013\022\033\n\027REPORT_ENVIRONMENT_DATA\020" +
      "\014\022\027\n\023REPORT_DRIVE_STATUS\020\r\022\032\n\026REPORT_OIL" +
      "_CONSUMPTION\020\016\022\031\n\025REPORT_DRIVE_BEHAVIOR\020" +
      "\017\022\026\n\022REPORT_DRIVE_SPEED\020\020\022\027\n\023REPORT_ENGI" +
      "NE_SPEED\020\021\022\030\n\024REPORT_ENGINE_STATUS\020\022\022\027\n\023" +
      "REPORT_BRAKING_INFO\020\023\022\025\n\021REPORT_TRIP_STA" +
      "RT\020\024\022\023\n\017REPORT_CAR_WARN\020\025\022\023\n\017REPORT_TRIP" +
      "_END\020\026\022\024\n\020REPORT_TYRE_INFO\020\027\022\023\n\017IOT_BROK" +
      "ER_INFO\020\030B(\n\036com.lyh.protobuf.demo.busin" +
      "essB\006Commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
